name: Build and Parse Secret to it

# EVENT
on:
  push:
  workflow_dispatch:
  repository_dispatch:

# ENVIRONMENT
env:
  MY_SECRET: ${{ secrets.MY_REPO_SECRET }}

# JOBS
jobs:
  #JOB1
  build:
    # RUNNER
    runs-on: ubuntu-latest

    # STEPS
    steps:
      # STEP1
      - name: run script
        run: ls -la

  # JOB 2
  run:
    runs-on: ubuntu-latest

    steps:
      # STEP1
      - uses: actions/checkout@v3
      
      # STEP2
      - name: Run the script
        run: |
          pwd
          ./run.sh "$MY_SECRET"
